# A project translates into one executable or library.
project:

  define:
    - USE_FULL_LL_DRIVER
    - USE_HAL_DRIVER
    - STM32H7S7xx

  add-path:
    - ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Inc
    - ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy
    - ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/CMSIS/Device/ST/STM32H7RSxx/Include
    - ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/CMSIS/Include
    - ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Appli/Core/Inc
    - ../STM32CubeMX/STM32H7S78-DK/MX_Device/Appli

  linker:
    - script: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/MDK-ARM/Appli/stm32h7rsxx_RAMxspi1_ROMxspi2.sct

  groups:
    - group: CubeMX
      files:
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/MDK-ARM/startup_stm32h7s7xx.s
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Appli/Core/Src/system_stm32h7rsxx.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Appli/Core/Src/main.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Appli/Core/Src/stm32h7rsxx_it.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Appli/Core/Src/stm32h7rsxx_hal_msp.c
    - group: STM32 HAL Driver
      files:
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_cortex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_rcc.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_rcc_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_flash.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_flash_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_gpio.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_dma.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_dma_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pwr.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pwr_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_exti.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_rcc.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_utils.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_exti.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_tim.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_tim_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_adc.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_adc_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_dcmipp.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_i2c.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_i2c_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_smbus.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_smbus_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_i2s.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_i2s_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_ltdc.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_ltdc_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_sdmmc.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_dlyb.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_sd.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_sd_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_spi.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_spi_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_uart.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_uart_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_ucpd.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_gpio.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_dma.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pcd.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pcd_ex.c
        - file: ../STM32CubeMX/STM32H7S78-DK/STM32CubeMX/Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_usb.c
    - group: Source Files
      files:
        - file: HID.c
        - file: USBD_User_HID.c
        - file: retarget_stdio.c

  # List components to use for your application.
  # A software component is a re-usable unit that may be configurable.
  components:
    - component: Keil::Device:CubeMX
    - component: ARM::CMSIS:CORE
    - component: ARM::CMSIS:OS Tick:SysTick
    - component: ARM::CMSIS:RTOS2:Keil RTX5&Source
    - component: ARM::CMSIS-Compiler:CORE
    - component: ARM::CMSIS-Compiler:STDIN:Custom
    - component: ARM::CMSIS-Compiler:STDOUT:Custom
    - component: ARM::CMSIS-Compiler:STDERR:Custom
    - component: Keil::CMSIS Driver:USART@3.0.0
    - component: Keil::CMSIS Driver:USB Device@3.0.0
    - component: Keil::CMSIS Driver:VIO:Board&STM32H7S78-DK
    - component: Keil::USB&MDK:CORE&Release
    - component: Keil::USB&MDK:Device
    - component: Keil::USB&MDK:Device:HID
